#
# Copyright 2023 Sanctum
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author: ms5984
#
# This workflow will build a Gradle project with JDK 17 and cache the build output.
# You can customize the Gradle command with the `gradle_args` input (defaults to 'build').
# Inputs:
#     gradle_args: String - The arguments to pass to Gradle. Defaults to `'build'`.
#     path: String - The paths to be cached. Defaults to `'**/build/libs/*.jar', '!buildSrc'`.
#     hash_pattern: String - Allows you to customize the files used to generate the cache key. See implementation notes for more details.
# Outputs:
#     path: String - The paths cached; same as the `path` input.
#     cache_key: String - The cache key for restoring Gradle's build output.
# Implementation notes:
# - The cache key is generated by hashing the contents of all .java, .kt, resources and buildscript files.
#   This should allow a cache hit on simple/cosmetic changes to the repository, such as to the README.md file.
#

name: Gradle Cache Build

on:
  workflow_call:
    inputs:
      gradle_args:
        description: The arguments to pass to Gradle
        required: false
        type: string
        default: build
      cache_save:
        description: Whether to cache the build
        required: false
        type: boolean
        default: true
      path:
        description: The paths to cache
        required: false
        type: string
        default: |
          **/build/libs/*.jar
          !buildSrc/**
      hash_pattern:
        description: The hash pattern(s) to use for generating the cache key
        required: false
        type: string
        default: |
          **/**.kts
          buildSrc/**
          **/src/*/**/java/**.java
          **/src/*/**/kotlin/**.kt
          **/src/*/resources/**
          **/gradle.properties
    outputs:
      path:
        description: The paths cached
        value: ${{ inputs.path }}
      cache_key:
        description: The cache key for restoring the Gradle build output
        value: ${{ jobs.build.outputs.cache_key }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache_key: ${{ steps.generate-cache-key.outputs.cache_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: generate-cache-key
        name: Generate cache key
        run: echo "cache_key=gradle-build-${{ hashFiles(inputs.hash_pattern) }}" >> $GITHUB_OUTPUT
      - name: Try to restore build output
        uses: actions/cache/restore@v3
        id: restore-build-output
        with:
          key: ${{ steps.generate-cache-key.outputs.cache_key }}
          path: ${{ inputs.path }}
      - name: Set up JDK 17
        if: steps.restore-build-output.outputs.cache-hit != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle [${{ inputs.gradle_args }}]
        if: steps.restore-build-output.outputs.cache-hit != 'true'
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: ${{ inputs.gradle_args }}
      - name: Cache new build output
        if: steps.restore-build-output.outputs.cache-hit != 'true' && inputs.cache_save
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.generate-cache-key.outputs.cache_key }}
          path: ${{ inputs.path }}
